steps:
- id: Build-docker
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/ecowave:$SHORT_SHA'
    - '.' 
  timeout: 900s

- id: Push-docker
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/ecowave:$SHORT_SHA'
  timeout: 900s

- id: Cloud-run
  name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'ecowave'
    - '--image'
    - 'gcr.io/$PROJECT_ID/ecowave:$SHORT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'DB_CONNECTION=mysql,DB_HOST=34.133.178.42,DB_PORT=3306,DB_NAME=ecowave_db,DB_USERNAME=root,DB_PASSWORD=secret-password'
  timeout: 900s
images:
- gcr.io/$PROJECT_ID/ecowave:$SHORT_SHA